name: test

on:
    push:
        branches:
            - dev
    pull_request:
        branches:
            - dev

concurrency:
    cancel-in-progress: true
    group: ${{github.workflow}}-${{github.ref}}

env:
    CARGO_TERM_COLOR: always

jobs:
    check:
      strategy:
        fail-fast: true

      name: zkSync Foundry Tests
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: install zksync fork
          run: |
            chmod +x ./install-foundry-zksync
            ./install-foundry-zksync
        - name: Verify Foundry installation
          run: |
            ~/.config/.foundry/bin/forge --version
        - name: Run Forge tests with zksync
          run: |
            ~/.config/.foundry/bin/forge test --zksync -vvv
